all:
	g++ -o auctionHouse main.cpp functions/showMenu/showMenu.cpp functions/addCredit/addCredit.cpp functions/advertise/advertise.cpp functions/bid/bid.cpp functions/create/create.cpp functions/delete/delete.cpp functions/refund/refund.cpp -std=c++11
clean:
	rm auctionHouse
